trigger:
  branches:
    include:
    - main

resources:
  repositories:
    - repository: templates
      type: git
      name: Plumbing/core-templates
    - repository: googlesignin-suitecrm
      type: git
      name: Open/googlesignin-suitecrm

stages:
- template: stages/sync/sync.yml@templates  # Template reference
  parameters:
    checkout: googlesignin-suitecrm
